package com.evac.app.db

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Room entity for safe spots (shelters, medical stations, food/water points).
 *
 * Designed for V2 Reverse-Mesh conflict resolution:
 * - [updatedAt] enables "last-write-wins" timestamp comparison
 * - [signature] is a placeholder for future Ed25519 cryptographic verification
 *
 * Do NOT use clearAll(). Individual upserts via [SafeSpotDao.upsertSpot] preserve
 * mesh-originated data that may have arrived out-of-order.
 */
@Entity(tableName = "safe_spots")
data class SafeSpotEntity(
    @PrimaryKey
    val id: String,                          // UUID generated by Commander Dashboard

    val name: String,                        // Human-readable spot name

    val latitude: Double,                    // GPS latitude

    val longitude: Double,                   // GPS longitude

    val type: String,                        // "MEDICAL", "SHELTER", "FOOD", "WATER", "POLICE"

    @ColumnInfo(name = "is_active")
    val isActive: Boolean = true,            // Whether this spot is currently operational

    @ColumnInfo(name = "updated_at")
    val updatedAt: Long,                     // Epoch millis — critical for mesh conflict resolution

    val signature: String? = null            // Nullable — V2 Ed25519 mesh verification placeholder
)
